// Internal prototype recipes: cooking and language content awaiting editorial review.
const it = ['Milan, IT', 'Roma, IT', 'Bologna, IT'];
const pt = ['Porto, PT', 'Lisbon, PT'];
function dish(id, language, name, minLevel, minutes, regions, ingredients, words, directions, tags = ['vegetarian'], image = 'vegetables') {
  return { id, language, name, minLevel, minutes, regions, ingredients, words, tags, image,
    description: `${name}: a new plate, a new conversation, and a little local discovery.`,
    steps: directions.map(([title, text], i) => [title, text, words[i % words.length][0], words[i % words.length][1]]),
    story: null, review: 'unreviewed',
  };
}
export const moreRecipes = [
  dish('coca', 'ca', 'Coca de verdures', 1, 45, ['Lleida, ES', 'Barcelona, ES'],
    ['250 g ready-made bread dough', '1 red pepper', '1 onion', '1 courgette', '2 tbsp olive oil', 'Salt'],
    [['massa','dough'],['pebrot','pepper'],['ceba','onion'],['carbassó','courgette']],
    [['Prepare the vegetables','Thinly slice the pepper, onion and courgette. Heat the oven to 220°C.'],['Stretch the dough','Stretch the dough onto an oiled baking tray. Leave a small edge.'],['Arrange the colors','Top with the vegetables, drizzle with oil and sprinkle with salt.'],['Bake and share','Bake for 20–25 minutes until the base is cooked and the vegetables are tender. Cut into portions.']], ['vegan'], 'bakery'),
  dish('mongetes', 'ca', 'Mongetes amb all', 0, 15, ['Girona, ES', 'Barcelona, ES'],
    ['400 g cooked white beans, drained', '2 garlic cloves', '1 tbsp olive oil', 'Parsley', 'Salt'],
    [['mongetes','beans'],['all','garlic'],['julivert','parsley'],['oli','oil']],
    [['Gather your ingredients','Drain and rinse the cooked beans. Finely chop the garlic and parsley.'],['Warm the garlic','Gently warm garlic in olive oil for a minute without browning it.'],['Add the beans','Stir in the beans and warm through for 5 minutes. Add a splash of water if needed.'],['Finish with parsley','Season and sprinkle with parsley. Describe the ingredients on your plate.']], ['vegan','gluten-free']),
  dish('crema', 'ca', 'Crema catalana', 2, 55, ['Barcelona, ES', 'Girona, ES', 'Lleida, ES'],
    ['500 ml milk', '4 egg yolks', '80 g sugar, plus topping', '20 g cornflour', 'Lemon peel', '1 cinnamon stick'],
    [['llet','milk'],['sucre','sugar'],['llimona','lemon'],['canyella','cinnamon']],
    [['Infuse the milk','Warm the milk with lemon peel and cinnamon. Remove from heat and infuse for 10 minutes.'],['Mix the base','Whisk egg yolks, sugar and cornflour. Slowly whisk in the strained warm milk.'],['Thicken gently','Return to low heat and stir continuously until thickened. Do not let it boil.'],['Chill the custard','Pour into heatproof ramekins and refrigerate until cold, at least 2 hours. This is extra chilling time beyond the active lesson.'],['Make a crisp top','Sprinkle a thin layer of sugar on each chilled custard. Caramelize carefully with a kitchen torch following its instructions.']], ['vegetarian','gluten-free'], 'bakery'),
  dish('espinacs', 'ca', 'Espinacs a la catalana', 0, 20, ['Barcelona, ES'],
    ['400 g fresh spinach', '30 g raisins', '30 g pine nuts', '2 garlic cloves', '2 tbsp olive oil', 'Salt'],
    [['espinacs','spinach'],['panses','raisins'],['pinyons','pine nuts'],['all','garlic']],
    [['Prepare everything','Wash the spinach. Soak the raisins in warm water for 10 minutes and slice the garlic.'],['Toast the pine nuts','Toast the pine nuts in a dry pan for a minute until golden, then set them aside.'],['Wilt the spinach','Warm the oil with the garlic, add the spinach and cook until it has wilted.'],['Add the raisins and serve','Stir in the drained raisins and pine nuts, season with salt and serve warm.']], ['vegan','gluten-free']),
  dish('calcots', 'ca', 'Calçots amb romesco', 1, 45, ['Valls, ES', 'Tarragona, ES'],
    ['12 calçots or thick spring onions', '2 ripe tomatoes', '30 g almonds', '30 g hazelnuts', '1 slice of bread', '1 garlic clove', '4 tbsp olive oil', '1 tbsp vinegar', 'Salt'],
    [['calçots','spring onions'],['salsa','sauce'],['ametlles','almonds'],['oli','oil']],
    [['Roast and toast','Heat the oven to 220°C. Roast the tomatoes and garlic for 20 minutes. Toast the almonds, hazelnuts and bread in a dry pan.'],['Blend the romesco','Blend the roasted tomatoes and garlic with the nuts, bread, oil, vinegar and salt until thick. Taste and adjust.'],['Char the calçots','Roast the calçots on a hot tray for 15 to 20 minutes, turning them, until the outsides are black and the insides soft.'],['Wrap, peel and dip','Wrap the hot calçots in paper for 10 minutes. Carefully peel off the black outer layer and dip in the romesco.']], ['vegan']),
  dish('samfaina', 'ca', 'Samfaina', 1, 40, ['Girona, ES', 'Tarragona, ES', 'Valls, ES'],
    ['1 aubergine', '1 courgette', '1 red pepper', '1 onion', '2 ripe tomatoes', '3 tbsp olive oil', 'Salt'],
    [['albergínia','aubergine'],['carbassó','courgette'],['pebrot','pepper'],['tomàquet','tomato']],
    [['Chop the vegetables','Cut the aubergine, courgette, pepper and onion into even, bite-sized pieces.'],['Start with the onion','Soften the onion and pepper in olive oil over a medium heat for about 10 minutes.'],['Add the rest','Add the aubergine and courgette and cook for 10 minutes, stirring now and then.'],['Simmer with tomato','Grate in the tomatoes, add salt and simmer gently for 15 minutes until thick and glossy.']], ['vegan','gluten-free']),
  dish('caprese', 'it', 'Insalata caprese', 0, 10, it,
    ['2 ripe tomatoes', '125 g vegetarian mozzarella', 'Basil', 'Olive oil', 'Salt'],
    [['pomodoro','tomato'],['mozzarella','mozzarella'],['basilico','basil'],['olio','oil']],
    [['Start with the colors','Wash the tomatoes and basil. Drain the mozzarella.'],['Slice and arrange','Slice the tomatoes and cheese. Alternate the slices on a plate.'],['Finish simply','Add basil, olive oil and a little salt. Name each ingredient before serving.']], ['vegetarian','gluten-free']),
  dish('cacio-pepe', 'it', 'Cacio e pepe', 2, 30, ['Roma, IT'],
    ['180 g spaghetti', '70 g finely grated Pecorino Romano', '1 tsp black pepper', 'Salt'],
    [['pasta','pasta'],['formaggio','cheese'],['pepe','pepper'],['acqua','water']],
    [['Prepare the cheese','Finely grate the cheese and grind the pepper. Bring a pan of lightly salted water to a boil.'],['Cook the pasta','Cook spaghetti according to the packet, reserving a cup of the starchy water.'],['Build the sauce','Briefly toast pepper in a dry pan. Mix the cheese with a little warm, not boiling, pasta water to form a paste.'],['Toss off the heat','Add drained pasta to the pepper pan off the heat. Toss in the cheese paste, loosening with warm pasta water until creamy.']], [], 'toast'),
  dish('tagliatelle', 'it', 'Tagliatelle ai funghi', 1, 25, ['Bologna, IT','Milan, IT'],
    ['180 g egg tagliatelle', '250 g mushrooms', '1 garlic clove', '2 tbsp olive oil', 'Parsley', 'Salt'],
    [['funghi','mushrooms'],['aglio','garlic'],['prezzemolo','parsley'],['pasta','pasta']],
    [['Slice and chop','Clean and slice mushrooms. Finely chop garlic and parsley.'],['Cook the mushrooms','Warm oil, add mushrooms and cook until their moisture evaporates. Add garlic for the final minute.'],['Boil the pasta','Cook tagliatelle according to packet directions. Reserve some pasta water.'],['Toss and serve','Toss pasta with mushrooms and a splash of cooking water. Finish with parsley.']], ['vegetarian']),
  dish('polenta', 'it', 'Polenta cremosa', 1, 25, ['Milan, IT','Bologna, IT','Roma, IT'],
    ['120 g quick-cooking polenta', '500 ml vegetable stock', '20 g butter', '30 g vegetarian hard cheese', 'Black pepper'],
    [['mais','corn'],['burro','butter'],['formaggio','cheese'],['brodo','stock']],
    [['Warm the stock','Bring the stock to a gentle simmer. Check the liquid ratio on your polenta packet and adjust if necessary.'],['Whisk the grains','Slowly pour in polenta while whisking to prevent lumps.'],['Stir and finish','Cook for the time specified on the packet, stirring. Remove from heat, add butter and cheese, and season.']], ['vegetarian','gluten-free']),
  dish('feijao-frade', 'pt', 'Salada de feijão-frade', 0, 12, pt,
    ['400 g cooked black-eyed beans, drained', '½ onion', '1 tomato', 'Parsley', 'Olive oil', 'Vinegar and salt'],
    [['feijão','beans'],['cebola','onion'],['salsa','parsley'],['tomate','tomato']],
    [['Meet the beans','Drain and rinse the cooked black-eyed beans.'],['Chop the vegetables','Finely dice the onion and tomato and chop the parsley.'],['Dress and share','Toss everything with olive oil, a little vinegar and salt. Taste and adjust.']], ['vegan','gluten-free']),
  dish('peixinhos', 'pt', 'Peixinhos da horta', 1, 30, pt,
    ['200 g green beans', '100 g flour', '1 egg', '120 ml sparkling water', 'Oil for shallow frying', 'Salt'],
    [['feijão-verde','green bean'],['farinha','flour'],['ovo','egg'],['óleo','oil']],
    [['Prepare the beans','Trim the green beans and blanch in boiling water for 3 minutes. Drain and dry thoroughly.'],['Make the batter','Whisk flour, egg and sparkling water into a light batter and add a pinch of salt.'],['Fry in small batches','Heat a shallow layer of oil in a heavy pan. Dip dry beans in batter and carefully fry in small batches until the batter is crisp. Keep water away from hot oil.'],['Drain and serve','Lift onto paper towel, allow to cool slightly, and serve. Describe the difference between the raw and cooked texture.']], ['vegetarian']),
  dish('acorda', 'pt', 'Açorda de coentros', 1, 25, pt,
    ['150 g stale bread', '2 garlic cloves', 'Coriander', '2 tbsp olive oil', '500 ml vegetable stock', '2 eggs'],
    [['pão','bread'],['alho','garlic'],['coentros','coriander'],['ovo','egg']],
    [['Prepare the bread','Tear the stale bread into a bowl. Chop garlic and coriander.'],['Make a fragrant base','Gently warm garlic in oil, add stock and bring to a simmer.'],['Cook the eggs','Poach the eggs in the stock until whites and yolks are set.'],['Bring it together','Pour stock over the bread, add coriander and top with the eggs. This is a simple home-kitchen adaptation.']], ['vegetarian'], 'toast'),
  dish('pao-queijo', 'pt', 'Pão de queijo', 1, 40, ['Rio, BR'],
    ['150 g tapioca starch', '100 ml milk', '40 ml oil', '1 egg', '80 g grated vegetarian hard cheese', 'Salt'],
    [['queijo','cheese'],['leite','milk'],['ovo','egg'],['polvilho','tapioca starch']],
    [['Warm the liquids','Heat oven to 200°C. Bring milk, oil and a pinch of salt just to a boil.'],['Mix the dough','Pour over tapioca starch and stir. Let cool until comfortable to handle, then mix in egg and cheese.'],['Shape small balls','With lightly oiled hands, form small balls and put on a lined tray with space between them.'],['Bake and share','Bake for 20–25 minutes until puffed and lightly golden. Let cool a little before eating.']], ['vegetarian','gluten-free'], 'bakery'),
  dish('brigadeiro', 'pt', 'Brigadeiro', 1, 35, ['Rio, BR'],
    ['1 can sweetened condensed milk (395 g)', '2 tbsp cocoa powder', '1 tbsp butter', 'Chocolate sprinkles'],
    [['leite condensado','condensed milk'],['cacau','cocoa'],['manteiga','butter'],['chocolate','chocolate']],
    [['Mix the base','Combine condensed milk, cocoa and butter in a heavy pan.'],['Keep stirring','Cook over low heat, stirring, until thick enough to pull away from the pan.'],['Cool completely','Transfer to a buttered plate. Allow to cool completely before handling; cooling adds time beyond the lesson.'],['Roll and finish','With buttered hands, roll into small balls and coat with sprinkles.']], ['vegetarian'], 'bakery'),

  dish('ensalada-tomate', 'es', 'Ensalada de tomate', 0, 10, [],
    ['3 ripe tomatoes', '½ onion', '2 tbsp olive oil', '1 tbsp vinegar', 'A pinch of salt'],
    [['tomate','tomato'],['cebolla','onion'],['aceite','oil'],['sal','salt']],
    [['Prepare the vegetables','Slice the tomatoes and cut the onion into thin rings.'],['Dress the salad','Arrange on a plate, drizzle with olive oil and vinegar and add a pinch of salt.'],['Let it rest','Leave for 5 minutes so the flavours mix, then serve.']], ['vegan','gluten-free']),
  dish('pisto', 'es', 'Pisto', 1, 35, [],
    ['1 courgette', '1 red pepper', '1 onion', '2 ripe tomatoes', '3 tbsp olive oil', 'Salt'],
    [['calabacín','courgette'],['pimiento','pepper'],['cebolla','onion'],['tomate','tomato']],
    [['Chop the vegetables','Cut the courgette, pepper and onion into small, even pieces.'],['Start with the onion','Soften the onion and pepper in olive oil over a medium heat for about 10 minutes.'],['Add the courgette','Add the courgette and cook for 10 minutes, stirring now and then.'],['Simmer with tomato','Grate in the tomatoes, add salt and simmer gently for 15 minutes until thick.']], ['vegan','gluten-free']),
  dish('tortilla', 'es', 'Tortilla de patatas', 2, 45, [],
    ['500 g potatoes', '1 onion', '5 eggs', '100 ml olive oil', 'Salt'],
    [['patatas','potatoes'],['cebolla','onion'],['huevos','eggs'],['aceite','oil']],
    [['Slice the potatoes and onion','Peel the potatoes and slice them thinly. Slice the onion too.'],['Poach in oil','Gently cook the potatoes and onion in olive oil over a low heat for about 20 minutes, until soft but not browned. Drain them, keeping a little oil.'],['Mix with the eggs','Beat the eggs with salt, stir in the warm potatoes and onion and let it sit for 5 minutes.'],['Set and flip','Cook in a pan over a medium heat for about 4 minutes, place a plate over the pan and carefully flip it, then cook the other side for 3 minutes.']], ['vegetarian','gluten-free']),
  dish('patatas-bravas', 'es', 'Patatas bravas', 1, 45, ['Madrid, ES'],
    ['500 g potatoes', '4 tbsp olive oil', '2 ripe tomatoes', '1 tsp smoked paprika', '1 garlic clove', 'Salt'],
    [['patatas','potatoes'],['tomate','tomato'],['pimentón','paprika'],['ajo','garlic']],
    [['Cut the potatoes','Cut the potatoes into bite-sized chunks and dry them well.'],['Roast the potatoes','Toss with oil and salt and roast at 220°C for about 35 minutes, turning once, until golden and crisp.'],['Make the spicy sauce','Warm the garlic and paprika in a little oil for 30 seconds, add the grated tomatoes and simmer for 10 minutes until thick. Blend it if you like.'],['Serve','Spoon the sauce over the hot potatoes and serve.']], ['vegan','gluten-free']),
  dish('ensaladilla', 'es', 'Ensaladilla rusa', 1, 40, ['Madrid, ES'],
    ['3 potatoes', '2 carrots', '100 g peas', '2 eggs', '3 tbsp mayonnaise', 'Salt'],
    [['patatas','potatoes'],['zanahorias','carrots'],['guisantes','peas'],['huevos','eggs']],
    [['Boil the vegetables','Boil the potatoes and carrots in salted water for about 20 minutes until tender, adding the peas for the last 3 minutes.'],['Boil the eggs','Boil the eggs for 10 minutes, then cool them in cold water and peel them.'],['Chop and cool','Dice the potatoes, carrots and eggs into small pieces and let everything cool completely.'],['Mix and chill','Stir in the mayonnaise and salt, then chill for at least 30 minutes before serving. This is extra chilling time beyond the active lesson.']], ['vegetarian','gluten-free']),
  dish('gazpacho', 'es', 'Gazpacho andaluz', 0, 15, ['Sevilla, ES'],
    ['1 kg ripe tomatoes', '1 cucumber', '1 green pepper', '1 garlic clove', '4 tbsp olive oil', '2 tbsp sherry vinegar', 'Salt'],
    [['tomates','tomatoes'],['pepino','cucumber'],['pimiento','pepper'],['ajo','garlic']],
    [['Chop everything','Roughly chop the tomatoes, cucumber and pepper, and peel the garlic.'],['Blend','Blend the vegetables with the oil, vinegar and salt until completely smooth.'],['Chill','Chill in the fridge for at least an hour. This is extra chilling time beyond the active lesson.'],['Serve cold','Taste, adjust the salt and vinegar, and serve very cold in glasses or bowls.']], ['vegan','gluten-free']),
  dish('salmorejo', 'es', 'Salmorejo', 1, 20, ['Sevilla, ES'],
    ['1 kg ripe tomatoes', '200 g stale bread', '1 garlic clove', '100 ml olive oil', '1 tbsp sherry vinegar', 'Salt'],
    [['tomates','tomatoes'],['pan','bread'],['ajo','garlic'],['aceite','oil']],
    [['Soak the bread','Tear the bread into pieces and soak it in a little water for a few minutes.'],['Blend the tomatoes','Blend the tomatoes with the garlic until smooth, then strain if you like.'],['Add the bread','Blend in the squeezed bread, then slowly pour in the oil until thick and creamy. Season with vinegar and salt.'],['Chill and serve','Chill for at least an hour, then serve cold. This is extra chilling time beyond the active lesson.']], ['vegan']),
  dish('espinacas-garbanzos', 'es', 'Espinacas con garbanzos', 1, 30, ['Sevilla, ES'],
    ['400 g cooked chickpeas', '300 g fresh spinach', '3 garlic cloves', '1 tsp smoked paprika', '3 tbsp olive oil', 'Salt'],
    [['garbanzos','chickpeas'],['espinacas','spinach'],['ajo','garlic'],['pimentón','paprika']],
    [['Prepare the ingredients','Drain and rinse the chickpeas and wash the spinach. Slice the garlic.'],['Fry the garlic','Warm the garlic in olive oil over a low heat for a minute without letting it brown, then take the pan off the heat and stir in the paprika.'],['Wilt the spinach','Return the pan to the heat, add the spinach and cook until it has wilted.'],['Add the chickpeas','Stir in the chickpeas with a splash of water and warm through for 5 minutes. Season with salt.']], ['vegan','gluten-free']),
  dish('paella-verduras', 'es', 'Paella de verduras', 2, 55, ['Valencia, ES'],
    ['300 g paella rice', '1 red pepper', '200 g green beans', '2 ripe tomatoes', '1 litre vegetable stock', 'A pinch of saffron', '4 tbsp olive oil', 'Salt'],
    [['arroz','rice'],['pimiento','pepper'],['judías verdes','green beans'],['azafrán','saffron']],
    [['Prepare the vegetables','Chop the pepper, trim the green beans and grate the tomatoes. Warm the stock with the saffron.'],['Fry the vegetables','Fry the pepper and green beans in olive oil in a wide pan for 8 minutes. Add the tomato and cook for 5 minutes.'],['Add the rice','Stir in the rice for a minute, then pour in the hot stock and add salt. Bring to a boil, then simmer without stirring for about 18 minutes.'],['Rest and serve','Take the pan off the heat, cover it and let it rest for 5 minutes before serving from the pan.']], ['vegan','gluten-free']),
];
